### ISSUE TITLE
Use f-strings

### ISSUE THREAD

**Issue by Fripe070** [TechnoShip123/Thonk-Bot#5]
Lines like these:
```
print(
print_info + bcolors.OKGREEN + bcolors.BOLD + "Successful Connection! " + bcolors.ENDC)
```
Could be replaced with something like this:
`print(f"{print_info}{bcolors.OKGREEN}{bcolors.BOLD}Successful Connection! {bcolors.ENDC}")`

**Comment by sjalkote** [comment]
Done! I'll optimize other parts similarly as well! Still not pulled from the dev branch since I need to verify some other bits of the code.
